# theme = "github_dark"
# theme = "catppuccin_mocha"
theme = "rose_pine_moon"

[editor]
bufferline = "multiple"
color-modes = true

# [editor.lsp]
# display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
# character = "|"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
'=' = ":format"

